version: 2.1
jobs:
  build:
    working_directory: ~/project/hello

    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: Version information
          command: |
            rustup --version
            rustc --version
            cargo --version

      - run:
          name: Calculate dependencies
          command: test -e Cargo.local || cargo generate-lockfile
      - run:
          name: Check formatting
          command: |
            if rustup component add rustfmt; then
              cargo fmt --all -- --check
            else
              echo Skipping rustfmt
            fi

