version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version; rustfmt --version

      - run:
          name: Print the Current Time
          command: date

